[project]
name = "ftp3sftp"
version = "0.4"
description = "A simple FTP to SFTP bridge. Fork of `ftp2sftp`."
requires-python = ">=3.9"
authors = [
  { name = "Iliya Iliev", email = "iliq0000@proton.me" },
  { name = "Sebastian Meyer", email = "sparrow.242.de@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "paramiko>=5.0.0",
  "pyftpdlib>=2.2.0",
]

[project.urls]
"Bug Tracker" = "https://github.com/iliqiliev/ftp3sftp/issues"
"Homepage" = "https://github.com/iliqiliev/ftp3sftp"

[project.scripts]
ftp3sftp = "ftp3sftp.ftp3sftp:main"

[build-system]
requires = ["uv_build>=0.11.19,<0.12"]
build-backend = "uv_build"
