[project]
name = "ftp3sftp"
version = "0.3"
description = "A simple FTP to SFTP bridge"
requires-python = ">=3.9"
authors = [
  { name = "Sebastian Meyer", email = "sparrow.242.de@gmail.com" },
  { name = "Iliya Iliev", email = "iliq0000@proton.me" }
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3"
]
dependencies = [
  "paramiko>=5.0.0",
  "pyftpdlib>=2.2.0",
]

[project.urls]
"Bug Tracker" = "https://gitlab.com/sparrow.242.de/ftp3sftp/-/issues"
"Homepage" = "https://gitlab.com/sparrow.242.de/ftp3sftp"

[project.scripts]
ftp3sftp = "ftp3sftp.ftp3sftp:main"

[build-system]
requires = ["uv_build>=0.11.19,<0.12"]
build-backend = "uv_build"
